---
- name: Package provision
  package:
    name: git, docker, docker-python
    state: '{{ wa_kat.state | default("present") }}'

- name: 'Clone WA-KAT: {{ wa_kat.release | default("HEAD") }} to {{ wa_kat.path | default ("/opt/git/wa-kat") }}'
  git:
   repo: 'https://github.com/WebarchivCZ/WA-KAT.git'
   accept_hostkey: True
   force: yes
   dest: '{{ wa_kat.path | default("/opt/git/wa-kat") }}'
   version: '{{ wa_kat.release | default("HEAD") }}'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Docker is running even after restart
  service:
    name: docker
    state: started
    enabled: True

- name: 'Building wa-kat: {{ wa_kat.release | default("HEAD") }} from repo'
  docker_image:
    path: '{{ wa_kat.path | default("/opt/git/wa-kat") }}'
    name: wa-kat
    tag: '{{ wa_kat.release | default("latest") }}'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'wa-kat: {{ wa_kat.release | default("latest") }} image is running'
  docker_container:
    name: 'wa-kat'
    image: 'wa-kat:{{ wa_kat.release | default("latest") }}'
    state: started
    ports: '{{ wa_kat.port | default("8080") }}:8080'
  ignore_errors: "{{ ansible_check_mode }}"
